feat(samples): add subordinate CA samples
googleapis/python-security-private-ca pull request #153
Opened 2021-11-19 17:15 UTC by FrodoTheTrue

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-security-private-ca/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2021-11-23 17:33 UTC, dinagraves requested changes
Thank you!  It's looking pretty good - make sure you replace all the camel case with snake case.  I added in some "suggestions", but you'll have to find all the references to it. 

LMK if you have any questions!

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/activate_subordinate_ca.py
> +    Activate a subordinate Certificate Authority.
```suggestion
    Activate a subordinate Certificate Authority (CA).
```

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/activate_subordinate_ca.py
> +    *Prerequisite*: Get the CSR of the subordinate CA signed by another CA. Pass in the signed
```suggestion
    *Prerequisite*: Get the Certificate Signing Resource (CSR) of the subordinate CA signed by another CA. Pass in the signed
```

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/activate_subordinate_ca.py
> +    Activate a subordinate Certificate Authority.
This is just a writing suggestion -- it helps the reader to spell out the full phrase first and then indicate that you'll be using the acronym later.

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/activate_subordinate_ca.py
> +    caServiceClient = privateca_v1.CertificateAuthorityServiceClient()
```suggestion
    ca_service_client = privateca_v1.CertificateAuthorityServiceClient()
```

Use snake case for python variables.  [PEP 8 Style Guide](https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables)

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/activate_subordinate_ca.py
> +        subordinate_config=privateca_v1.SubordinateConfig(
I wonder if it would be better to construct this outside of the function call? I feel like it's getting a little lost nested in here.

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/activate_subordinate_ca.py
> +    time.sleep(3)
Why sleep here?  Can you add a comment explaining it?

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/create_certificate_csr.py
> +    Create a Certificate which is issued by the specified Certificate Authority.
```suggestion
    Create a Certificate which is issued by the specified Certificate Authority (CA).
```

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/create_certificate_csr.py
> +    The certificate details and the public key is provided as a CSR (Certificate Signing Request).
```suggestion
    The certificate details and the public key is provided as a Certificate Signing Request (CSR).
```

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/create_certificate_csr.py
> +    caServiceClient = privateca_v1.CertificateAuthorityServiceClient()
```suggestion
    ca_service_client = privateca_v1.CertificateAuthorityServiceClient()
```

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/create_certificate_csr.py
> +    certificate = certificate = privateca_v1.Certificate(
`certificate = certificate =  ... `

I'm not clear what's happening here.  Is this a typo?  If not, can you add a comment?

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/create_certificate_csr.py
> +    print("Certificate created successfully: " + response.name)
```suggestion
    print(f"Certificate created successfully: {response.name}")
```

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/create_subordinate_ca.py
> +    Create Certificate Authority which is the subordinate CA in the given CA Pool.
```suggestion
    Create Certificate Authority (CA) which is the subordinate CA in the given CA Pool.
```

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/create_subordinate_ca.py
> +    caServiceClient = privateca_v1.CertificateAuthorityServiceClient()
```suggestion
    ca_service_client = privateca_v1.CertificateAuthorityServiceClient()
```

2021-11-23 17:33 UTC, dinagraves commented on samples/snippets/create_subordinate_ca.py
> +    print("Operation result:", result)
```suggestion
    print(f"Operation result: result")
```

2021-11-25 21:16 UTC, FrodoTheTrue commented
@dinagraves thanks for the review. updated!

2021-11-26 11:47 UTC, dinagraves approved these changes
Awesome! Looking good!  Found one more spot with the camel case that should be switched to snake case.  

Approving now - please update before you merge!  Thank you!

2021-11-26 11:47 UTC, dinagraves commented on samples/snippets/test_subordinate_ca.py
> +    caServiceClient = privateca_v1.CertificateAuthorityServiceClient()
```suggestion
    ca_service_client = privateca_v1.CertificateAuthorityServiceClient()
```

2021-11-29 09:57 UTC, merged